name: Tag on Version Change

on:
  push:
    paths:
      - "Cargo.toml"  # Trigger workflow only when Cargo.toml changes

jobs:
  tag-version:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is available for tagging

      # Step 2: Set up Git user
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Extract version from Cargo.toml and create a tag
      - name: Extract version and create tag
        id: tag_version
        run: |
          # Extract version from Cargo.toml
          VERSION=$(grep '^version' Cargo.toml | sed -E 's/version = "(.*)"/\1/')
          echo "Extracted version: $VERSION"

          # Check if the version was extracted correctly
          if [ -z "$VERSION" ]; then
            echo "Error: Version could not be extracted from Cargo.toml."
            exit 1
          fi

          # Check if the tag already exists
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "Tag v$VERSION already exists. Skipping tag creation."
            exit 0
          fi

          # Create the Git tag
          git tag "v$VERSION"
          echo "Tag v$VERSION created."

      # Step 4: Push the tag to GitHub
      - name: Push tag to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin "v$VERSION"

