name: Tag and Release on Version Change

on:
  push:
    paths:
      - "Cargo.toml"
  workflow_dispatch:

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for tagging

      # Step 2: Set up Rust environment (optional, for version extraction)
      - name: Set up Rust
        uses: actions/setup-rust@v1

      # Step 3: Extract version from Cargo.toml
      - name: Extract version from Cargo.toml
        id: get_version
        run: |
          VERSION=$(awk -F\" '/^version =/ { print $2 }' Cargo.toml)
          echo "Version extracted: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Step 4: Create Tag and Release
      - name: Create Tag and Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          body: |
            ## Changes in this release
            - Describe your changes here.
          draft: false
          prerelease: false

